[env:nano]
platform      = atmelavr
board         = nanoatmega328
framework     = arduino
monitor_speed = 115200

; 'pre:' significa que se ejecuta antes de compilar.
extra_scripts = pre:lib/CoreFSM/tools/wokwi2corefsm.py

build_flags = -Wall