; =============================================================================
;  MiRobotKeyestudio
; -----------------------------------------------------------------------------
;  Generado por nuevo_proyecto.py. Abre ESTA carpeta en VS Code, no la raiz del
;  repositorio: PlatformIO busca el platformio.ini en la raiz de lo que abras.
; =============================================================================

[env:nano]
platform      = atmelavr
board         = uno
framework     = arduino
upload_port   = COM3
monitor_speed = 115200

lib_extra_dirs = ../../lib
extra_scripts  = pre:../../lib/CoreFSM/tools/corefsm_gen.py
build_flags =
  -Wall
  -I obj